
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.gatewayapi.kong.com
  resources:
  - kongs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.gatewayapi.kong.com
  resources:
  - kongs/finalizers
  verbs:
  - update
- apiGroups:
  - operator.gatewayapi.kong.com
  resources:
  - kongs/status
  verbs:
  - get
  - patch
  - update
